name: CI/CD do Projeto Java
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest # O executar será uma maquina Ubuntu mais recente

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action para clonar o repositório

      - name: Set up Java
        uses: actions/setup-java@v4 # Action específica para configurar o Java JDK
        with:
          java-version: '17' # A versão do JDk necessário
          distribution: 'temurin' # Distribução do JDK
          cache: maven # Habilita o cache de dependencias do Maven

      - name: Build Jar
        run: mvn -B package --file pom.xml

      - name: Login on GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOkeN }}

      - name: build and publish Image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          # Exemplo de build args se seu Dockerfile precisar:
          # build-args: |
          #   JAR_FILE=target/sua-aplicacao.jar
